export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export type FETCH_EVENTS_REQUEST = typeof FETCH_EVENTS_REQUEST;

export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export type FETCH_EVENTS_SUCCESS = typeof FETCH_EVENTS_SUCCESS;

export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';
export type FETCH_EVENTS_FAILURE = typeof FETCH_EVENTS_FAILURE;
