const {
  PL_SITE_URL,
  NODE_ENV,
  URL: NETLIFY_SITE_URL = PL_SITE_URL,
  DEPLOY_PRIME_URL: NETLIFY_DEPLOY_URL = NETLIFY_SITE_URL,
  CONTEXT: NETLIFY_ENV = NODE_ENV,
} = process.env;

const SITE_URL = NETLIFY_ENV === 'production' ? NETLIFY_SITE_URL : NETLIFY_DEPLOY_URL;

module.exports = {
  NETLIFY_SITE_URL,
  NETLIFY_DEPLOY_URL,
  NETLIFY_ENV,
  SITE_URL,
};
